name: dashboards
channels:
  - eoas_ubc
  - conda-forge
  - defaults
dependencies:
  - python=3.7.*
  - pandas
  - numpy
  - matplotlib
  - plotly
  - jupyter
  - jupytext
  - sphinx
  - ipython=7.0
  - scipy
  - git
  - runjb
  - ghp-import
  - click
  - jupyterlab
  - toml
  - pyarrow
  - voila
  - ipyleaflet
  - ipywidgets
  - ipyvolume
  - ipympl
  - bqplot
  - conda-lock
  - pip
# conda-lock -f environment.yml -p linux-64
